# name: Deploy NestJS

# on:
#   push:
#     branches: [main]

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20
#       - run: npm install
#         working-directory: ./backend
#       - run: npm run build
#         working-directory: ./backend
#       - name: Build Docker
#         run: docker build -t my-nest ./backend
#       - name: Push Docker
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       - run: docker push mydockerhubuser/my-nest:latest
#       - name: Deploy on server
#         uses: appleboy/ssh-action@v0.1.9
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             docker pull mydockerhubuser/my-nest:latest
#             docker stop nest || true
#             docker rm nest || true
#             docker run -d --name nest -p 4000:4000 mydockerhubuser/my-nest:latest
name: Deploy NestJS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/deploy/backend
            git pull origin main
            npm install --production
            npm run build
            pm2 restart nest || pm2 start dist/main.js --name nest
